title: Github Test Site
author: audiomason
description: > # this means to ignore newlines until "baseurl:"
  Test site created following the github pages tutorial.

# social links
twitter_username: audiomason
github_username:  audiomason

show_excerpts: false # set to false to remove excerpts on the homepage

theme: minima
